name: API Deployment workflow

# Controls when the action will run.
on:
  workflow_dispatch:
  push:

jobs:
  test-rest-api:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install dependencies
#          python -m pip install --upgrade pip
        run: |
          pip install -r ./starter/requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
