name: Deployment workflow

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  test-transition-issue:
    name: API Deployment
    runs-on: ubuntu-latest

    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1

      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set up Python 2.8.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
